### ISSUE TITLE
SAR-Ship-Dataset

### ISSUE THREAD

**Issue by yjwtt** [nasir6/sar-vessel-detection-deeplearning#1]
When i downloaded the SAR-Ship-Dataset from the link and extracted it, unknown probelm occured and i failed to texracted it. Would you please sent the dataset to me? My email address is 570414788@qq.com . Thanks a lot~

**Comment by GanggangDong** [comment]
@yjwtt @nasir6 Would you like to share me a copy of the dataset? THX...

**Comment by ojasvi21nov** [comment]
please share the data.  ojasvi21nov@gmail.com

**Comment by ani16** [comment]
Hello

Please any one could share ship dataset over anishi.anishi@gmail.com

**Comment by ani16** [comment]
I really need it urgently

**Comment by GanggangDong** [comment]
I would like to share part of the dataset. Yet I could not get access to gmail.

**Comment by ErginGokkaya** [comment]
could anyone share the dataset to me please ? email: ergingokkaya.eg@gmail.com

**Comment by nasir6** [comment]
shared [data on google drive](https://drive.google.com/file/d/13xLggEmn2gPb2P9iigu__eJBAhsq5lds/view?usp=sharing)
